knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        # will create service: "knpu.oauth2.client.keycloak"
        # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\KeycloakClient
        # composer require stevenmaguire/oauth2-keycloak
        keycloak:
            # must be "keycloak" - it activates that type!
            type: keycloak
            # add and set these environment variables in your .env files
            client_id: '%env(KEYCLOAK_OIDC_CLIENT_ID)%'
            client_secret: '%env(KEYCLOAK_OIDC_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: oidc_callback
            redirect_params: { }
            # Keycloak server URL
            auth_server_url: http://localhost:8081
            # Keycloak realm
            realm: local-dev
            # Optional: Encryption algorithm, i.e. RS256
            encryption_algorithm: RS256
            # Optional: Encryption key path, i.e. ../key.pem
            # encryption_key_path: null
            # Optional: Encryption key, i.e. contents of key or certificate
            # encryption_key: null
            # Optional: The keycloak version to run against
            # version: '20.0.1'
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
